services:
  docs:
    container_name: conecta.surister.dev
    image: nginx
    restart: unless-stopped
    networks:
      - proxy
    ports:
      - 80
    environment:
      - VIRTUAL_HOST=conecta.surister.dev
      - NGINX_HOST=conecta.surister.dev
    volumes:
      - ./site/:/usr/share/nginx/html

networks:
  proxy:
    name: proxy
    external: true