site_name: Conecta documentation
watch: [./docs/]
nav:
  - Project:
      - Overview: index.md
      - Setup: setup.md
      - Development: development.md
  - Source databases:
      - Postgres: databases/postgres.md
  - Arrow backends: arrow_backends.md
  - Optimizing further: optimizing.md

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
  features:
    - content.code.copy
plugins:
  - search
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings:
      handlers:
        python:
          paths: [., conecta-python, conecta-python/*, ..]
          import:
          - https://docs.python.org/3/objects.inv
          options:
            docstring_options:
              ignore_init_summary: true
            docstring_section_style: list
            heading_level: 1
            inherited_members: true
            merge_init_into_class: true
            separate_signature: true
            show_root_heading: true
            show_root_full_path: false
            show_signature_annotations: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
repo_name: Conecta
repo_url: https://www.github.com/surister/conecta
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - tables
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
