name: Test conecta-core

on:
  # allows to be called from other workflow
  workflow_call:

  workflow_dispatch:
  push:
    paths-ignore:
      - '*.py'
      - '*.md'
    branches:
      - master
  pull_request:
    paths-ignore:
      - '*.py'
      - '*.md'
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
    steps:
      - uses: actions/checkout@v5
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
        working-directory: conecta-core
      - run: cargo fmt --check
        working-directory: conecta-core
      - run: cargo test --lib --bins --tests --verbose
        working-directory: conecta-core